#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  cloudflareLegacyRedirectLine,
  cloudflareLegacyRedirectSource,
} from './legacy-redirects.mjs'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const check = process.argv.includes('--check')

function stableJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`
}

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'))
}

async function output(path, contents) {
  if (check) {
    let existing = ''
    try {
      existing = await readFile(path, 'utf8')
    } catch {
      throw new Error(`${path} has not been generated`)
    }
    if (existing !== contents) throw new Error(`${path} is stale; run pnpm generate`)
    return
  }
  await writeFile(path, contents)
}

const catalog = await readJson(resolve(root, 'src/data/logos.json'))
const searchIndex = [...catalog.logos]
  .sort((left, right) => left.slug.localeCompare(right.slug, 'en'))
  .map(({ slug, name, aliases, category }) => ({ slug, name, aliases, category }))

let idMap = { logos: [] }
try {
  idMap = await readJson(resolve(root, 'migration/legacy-id-map.json'))
} catch (error) {
  if (catalog.logos.length > 0) throw error
}

const dynamicLegacyRedirects = idMap.logos.filter((entry) =>
  cloudflareLegacyRedirectSource(entry).includes('*')
)
if (dynamicLegacyRedirects.length > 100) {
  throw new Error('legacy redirect count exceeds the Cloudflare Pages dynamic redirect budget')
}
if (idMap.logos.length - dynamicLegacyRedirects.length > 1_900) {
  throw new Error('legacy redirect count exceeds the reserved Cloudflare Pages static redirect budget')
}

const redirectLines = [
  '# Generated by scripts/generate-static.mjs. Do not edit by hand.',
  ...idMap.logos.map(cloudflareLegacyRedirectLine),
  '/upload /submit/ 301',
  '/upload/ /submit/ 301',
  '/uploadSuccess /submit/ 301',
  '/uploadSuccess/ /submit/ 301',
  '/successful /submit/ 301',
  '/successful/ /submit/ 301',
  '/personal / 301',
  '/personal/ / 301',
  '',
]

await output(resolve(root, 'public/search-index.json'), stableJson(searchIndex))
await output(resolve(root, 'public/_redirects'), redirectLines.join('\n'))

console.log(`Generated search index and redirects for ${catalog.logos.length} logos.`)
